"""Add BankAccounts

Revision ID: 23962cf7f4a1
Revises: e7d7b833a765
Create Date: 2023-06-16 16:46:51.864894

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '23962cf7f4a1'
down_revision = 'e7d7b833a765'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.DECIMAL(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
