"""Add constraint for balance

Revision ID: 4af477da8466
Revises: da1cfc964f37
Create Date: 2023-06-20 14:49:27.777640

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4af477da8466'
down_revision = 'da1cfc964f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('only_positive_balance', 'billing_accounts',
                               'balance > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('only_positive_balance', 'billing_accounts')
    # ### end Alembic commands ###
