"""Init Database

Revision ID: 4ea566480597
Revises: 
Create Date: 2023-06-16 16:31:11.207252

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4ea566480597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
