"""Add price in ProductModel

Revision ID: 4f3dbf6d08fc
Revises: 6992586e037c
Create Date: 2023-06-19 16:01:14.601241

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4f3dbf6d08fc'
down_revision = '6992586e037c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE products SET price = 0')
    op.alter_column('products', 'price', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
