"""Add is_active in UserModel

Revision ID: 6992586e037c
Revises: 4e02fe340f86
Create Date: 2023-06-19 14:40:28.838206

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6992586e037c'
down_revision = '4e02fe340f86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE users SET is_active = false')
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
