"""Add BlackListToken table

Revision ID: 84525e8ae677
Revises: 4af477da8466
Create Date: 2023-06-23 08:36:05.528094

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '84525e8ae677'
down_revision = '4af477da8466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_list_token_jti'), 'black_list_token', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_black_list_token_jti'), table_name='black_list_token')
    op.drop_table('black_list_token')
    # ### end Alembic commands ###
