"""Rename table BillingAccounts

Revision ID: da1cfc964f37
Revises: b49f363a7ee9
Create Date: 2023-06-20 11:48:58.800996

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'da1cfc964f37'
down_revision = 'b49f363a7ee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('bank_accounts', 'billing_accounts')
    op.drop_constraint('transactions_bank_account_id_fkey', 'transactions', 'foreignkey')
    op.create_foreign_key(
        constraint_name='transactions_bank_account_id_fkey',
        source_table='transactions',
        referent_table='billing_accounts',
        local_cols=['bank_account_id'],
        remote_cols=['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('billing_accounts', 'bank_accounts')
    op.drop_constraint('transactions_bank_account_id_fkey', 'transactions', 'foreignkey')
    op.create_foreign_key(
        constraint_name='transactions_bank_account_id_fkey',
        source_table='transactions',
        referent_table='bank_accounts',
        local_cols=['bank_account_id'],
        remote_cols=['id'],
    )
    # ### end Alembic commands ###
